routes/email_routes.py
import os
from flask import render_template, Blueprint, request, flash, get_flashed_messages, redirect, url_for
from dotenv import load_dotenv

import requests
from movie_web_app.data_manager.sqlite_data_manager import SQLiteDataManager
from movie_web_app.helpers.helper_functions import generate_secure_password
from movie_web_app.helpers.helper_functions import bcrypt
from movie_web_app.helpers.chat_gpt_interface import ai_interface, ai_prompt, ai_welcome

load_dotenv()

email_bp = Blueprint('email_bp', __name__)

DATABASE_FILE = os.getenv('DATABASE_FILE')
data_manager = SQLiteDataManager(DATABASE_FILE)

ELASTIC_EMAIL_API_KEY = os.getenv('ELASTICMAILAPIKEY')


def send_notification(subject, recipient, message_body):
    url = 'https://api.elasticemail.com/v2/email/send'
    payload = {
        'apikey': ELASTIC_EMAIL_API_KEY,
        'to': recipient,
        'subject': subject,
        'bodyHtml': message_body,
        'from': 'moviepedia.app@gmail.com'
    }
    response = requests.post(url, data=payload)
    return response.json()


def welcome_email(user_id):
    user = data_manager.get_user_emails(user_id)[0]
    user_name = user['username']
    user_email = user['email']

    welcome_message = ai_interface(ai_welcome(user_name))
    subject = "Welcome to Moviepedia"
    recipient = user_email
    message_body = welcome_message

    response = send_notification(subject, recipient, message_body)
    print(f"Notification sent! Response: {response}")



@email_bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
    """ Updates the user password with a random generated code and sends
    "an email notification to the user with the code to reset his password"""
    try:
        if request.method == 'POST':
            # Get email input
            input_email = request.form.get('email')
            try:
                # check if email address is in database (create a data_manager method)
                user_data = data_manager.check_email_address(input_email)
            except ValueError as e:
                flash(str(e), 'error')
                return redirect(url_for('email_bp.forgot_password'))

            # generate a new password for the user
            new_password = generate_secure_password()
            hashed_password = bcrypt.generate_password_hash(new_password).decode('utf-8')

            # update the password to the new one (do not forget bcrypt)
            user_id = user_data[0]['ID']
            data_manager.update_password(user_id, hashed_password)

            # send email to the user with the new temporary password and instructions to change it
            # Render the HTML template with the new password
            html_content = render_template('email_reset_password.html', new_password=new_password)

            user_email = user_data[0]['email']
            subject = "Moviepedia Password Reset"
            recipient = user_email
            message_body = html_content

            response = send_notification(subject, recipient, message_body)
            print(f"Notification sent! Response: {response}")
            flash('Email sent!', 'success')
            return redirect(url_for('email_bp.forgot_password'))

        # render template to insert user email address
        success_messages = get_flashed_messages(category_filter=['success'])
        error_messages = get_flashed_messages(category_filter=['error'])
        return render_template('forgot_password.html', error_messages=error_messages, success_messages=success_messages)

    except ValueError as e:
        error_message = str(e)
        return render_template('general_error.html', error_message=error_message)

    except RuntimeError as e:
        error_message = "Error retrieving data from database"
        print(f"Error: {str(e)}")
        return render_template('general_error.html', error_message=error_message)


@email_bp.route('/ai_recommends/<user_id>', methods=['GET', 'POST'])
def ai_recommendations(user_id):
    if request.method == 'POST':
        user = data_manager.get_user_emails(user_id)[0]
        user_id = user['ID']
        user_name = user['username']
        user_email = user['email']
        movies = data_manager.get_user_movies(user_id)
        user_fav_movies = []
        for movie in movies:
            user_fav_movies.append(movie['title'])

        user_recommendations = ai_interface(ai_prompt(user_name, user_fav_movies))
        html_content = user_recommendations

        subject = "Your Moviepedia Recommendations"
        recipient = user_email
        message_body = html_content

        response = send_notification(subject, recipient, message_body)
        print(f"Notification sent! Response: {response}")

        flash('Email sent! Check the spam!!', 'success')
        return redirect(url_for('movie_bp.user_movies', user_id=user_id))

routes/user_routes.py
import os

from dotenv import load_dotenv
from flask import render_template, request, redirect, url_for, Blueprint

from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from movie_web_app.helpers.helper_functions import bcrypt

from movie_web_app.data_manager.sqlite_data_manager import SQLiteDataManager
from movie_web_app.data_manager.user import User
from movie_web_app.helpers.authentication_helpers import is_valid_password
from movie_web_app.helpers.helper_functions import id_generator
from .email_routes import welcome_email

load_dotenv()

# Create the user_bp Blueprint
user_bp = Blueprint('user_bp', __name__)

DATABASE_FILE = os.getenv('DATABASE_FILE')
data_manager = SQLiteDataManager(DATABASE_FILE)
login_manager = LoginManager()


@user_bp.route('/')
def home():
    """Renders the homepage template."""
    show_my_movies_button = False
    if current_user.is_authenticated:
        show_my_movies_button = True
    return render_template('homepage.html', show_my_movies_button=show_my_movies_button)


@user_bp.route('/users')
def list_users():
    """Retrieves all users and renders the users template."""
    try:
        users = data_manager.get_all_users()
        return render_template('users.html', users=users)
    except TypeError as te:
        print(f"Error: {str(te)}")
        return render_template('general_error.html', error_message="Error retrieving users data")
    except IOError as e:
        error_message = "An error occurred while retrieving user data."
        print(f"IOError: {str(e)}")
        return render_template('general_error.html', error_message=error_message)
    except RuntimeError as e:
        error_message = "An unexpected error occurred."
        print(f"Error: {str(e)}")
        return render_template('general_error.html', error_message=error_message)


@user_bp.route('/add_user', methods=['GET', 'POST'])
def add_user():
    """Adds a new user to the system."""
    if request.method == 'POST':
        user_name = request.form.get('name')
        user_password = request.form.get('password')
        email = request.form.get('email')

        try:
            if is_valid_password(user_password):
                encrypted_password = bcrypt.generate_password_hash(user_password).decode('utf-8')
                user_id = id_generator()

                # Call the add_user method and check if the user was added successfully
                if data_manager.add_user(user_name, encrypted_password, user_id, email):
                    welcome_email(user_id)
                    print('email sent')
                    return redirect(url_for('user_bp.login', username=user_name))
                else:
                    error_message = "Username already exists. Please choose a different username."
                    return render_template('add_user.html', error_message=error_message)
            else:
                error_message = "Invalid password. Password needs to have at least 8 characters, " \
                                "one uppercase letter, one number and one special character."
                return render_template('add_user.html', error_message=error_message)

        except ValueError as e:
            return render_template('add_user.html', error_message=str(e))
        except IOError as e:
            error_message = "An error occurred while adding a new user."
            print(f"IOError: {str(e)}")
            return render_template('general_error.html', error_message=error_message)
        except RuntimeError as e:
            error_message = "An unexpected error occurred."
            print(f"Error: {str(e)}")
            return render_template('general_error.html', error_message=error_message)

    return render_template('add_user.html')


@user_bp.route('/users/<user_id>/manage_account', methods=['GET'])
@login_required
def manage_account(user_id):
    """Renders the manage account page for a specific user."""
    return render_template('manage_account.html', user_id=user_id)


@user_bp.route('/users/<user_id>/manage_account/update_password', methods=['GET', 'POST'])
@login_required
def change_password(user_id):
    """Updates the password for a specific user."""
    if request.method == 'POST':
        current_password = request.form.get('current_password')
        new_password = request.form.get('new_password')
        try:
            user_data = data_manager.get_user_data()
            user = next(user for user in user_data if user['id'] == user_id)
            if user and bcrypt.check_password_hash(user['password'], current_password):
                if is_valid_password(new_password):
                    encrypted_password = bcrypt.generate_password_hash(new_password).decode('utf-8')
                    data_manager.update_password(user_id, encrypted_password)
                    message = "Password successfully updated"
                    return render_template('successfully_changed_password.html', message=message, user_id=user_id)

                else:
                    error_message = "Invalid password. Password needs to have at least 8 characters, " \
                                    "one uppercase letter, one number and one special character."
                    return render_template('change_password.html', error_message=error_message)
            else:
                error_message = "Password Incorrect, please try again"
                return render_template('change_password.html', error_message=error_message)

        except ValueError as ve:
            return render_template('general_error.html', error_message=str(ve))
        except TypeError as te:
            print(f"Error: {str(te)}")
            return render_template('general_error.html', error_message="Error retrieving user data")
        except IOError as e:
            error_message = "An error occurred while updating the password."
            print(f"IOError: {str(e)}")
            return render_template('general_error.html', error_message=error_message)
        except RuntimeError as e:
            error_message = "An unexpected error occurred."
            print(f"Error: {str(e)}")
            return render_template('general_error.html', error_message=error_message)

    return render_template('change_password.html', user_id=user_id)


@user_bp.route('/users/<user_id>/manage_account/delete_user', methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
    """Deletes a user and all its associated movies """
    if request.method == 'POST':
        user_password = request.form.get('password')
        user_password_2 = request.form.get('confirm_password')

        if user_password == user_password_2:
            try:
                user_data = data_manager.get_user_data()
                for user in user_data:
                    if bcrypt.check_password_hash(user['password'], user_password):
                        data_manager.delete_user(user_id)
                        return redirect(url_for('user_bp.home'))

            except ValueError as e:
                error_message = str(e)
                return render_template('general_error.html', error_message=error_message)
            except RuntimeError as e:
                error_message = str(e)
                return render_template('general_error.html', error_message=error_message)

        else:
            error_message = 'Passwords need to match'
            return render_template('delete_user.html', error_message=error_message)

    return render_template('delete_user.html')


@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    """Authenticates the user and logs them in"""
    if request.method == 'POST':
        username = request.form.get('username')
        user_password = request.form.get('password')

        try:
            user_data = data_manager.get_user_data()
            for user in user_data:
                if user['name'] == username and bcrypt.check_password_hash(user['password'], user_password):
                    user_obj = User(user)  # Create an instance of the User class
                    login_user(user_obj)
                    user_id = user['id']
                    return redirect(url_for('movie_bp.user_movies', user_id=user_id))
            else:
                error_message = "Username or password Incorrect, please try again"
                return render_template('login.html', error_message=error_message)

        except IOError as e:
            error_message = "An error occurred while logging in."
            print(f"IOError: {str(e)}")
            return render_template('general_error.html', error_message=error_message)
        except RuntimeError as e:
            error_message = "An unexpected error occurred."
            print(f"Error: {str(e)}")
            return render_template('general_error.html', error_message=error_message)

    return render_template('login.html')


@user_bp.route('/logout')
@login_required
def logout():
    """Logs out the currently logged-in user."""
    logout_user()
    return redirect(url_for('user_bp.home'))

templates/401.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>401</title>
  <link rel="stylesheet" href="/static/general-style.css">
</head>
<body>
<div class="title">
    <h1> Unauthorized </h1>
</div>
<p> The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.</p>

<div class="buttons-container">
   <a href="{{ url_for('user_bp.home') }}">
        <button class="top-right-button">Back to Homepage</button>
    </a>
</div
</body>
</html>

templates/add_movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Movie</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='add-movie-style.css') }}">
</head>
<body>

<div class="title">
    <h1>Add Movie</h1>
</div>

<div class="add-movie-box">
    <div class="enter-movie-box">
        <form method="POST" action="{{ url_for('movie_bp.add_movie', user_id=user_id) }}">
            <label for="movie">Enter Movie:</label>
            <input type="text" name="movie" id="movie" required> <button type="submit">Add</button>
        </form>
    </div>
</div>

<div class="button-container">
    <a href="{{ url_for('movie_bp.user_movies', user_id=user_id) }}">
        <button class="bottom-right-button">Back to my Movies</button>
    </a>

    <a href="{{ url_for('user_bp.home') }}">
        <button class="bottom-right-button">Back to Homepage</button>
    </a>

    <a href="{{ url_for('user_bp.list_users') }}">
        <button class="bottom-right-button">Back to all users</button>
    </a>
</div>

</body>
</html>

templates/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Review</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='add-review-style.css') }}">
</head>
<body>

<div class="title">
    <h1>Add Review</h1>
</div>

<div class="add-review-box">
    <div class="enter-review-box">
        <form method="POST" action="{{ url_for('review_bp.add_review', user_id=user_id, movie_id=movie_id) }}">
            <label for="rating">Rating:</label>
            <input type="number" name="rating" id="rating" min="1" max="10" step="0.1" required><br>

            <label for="review_title">Title:</label>
            <input type="text" name="review_title" id="review_title" required><br>

            <label for="review_text">Review:</label>
            <textarea name="review_text" id="review_text" rows="4" required></textarea><br>

            <button type="submit">Add Review</button>
        </form>
    </div>
</div>

<div class="button-container">
    <a href="{{ url_for('review_bp.movie_details', movie_id=movie_id) }}">
        <button class="bottom-right-button"> Back to Movie Details </button>
    </a>
</div>

</body>
</html>

templates/add_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add User</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='add-user-style.css') }}">
</head>
<body>

<div class="title">
    <h1>New User</h1>
</div>

<div class="add-user-box">
    <div class="enter-user-box">
        <form method="POST" action="{{ url_for('user_bp.add_user') }}">

            <label for="email">Email:</label>
            <input type="text" name="email" id="email" value="{{ email }}" required><br>

            <label for="name">Username:</label>
            <input type="text" name="name" id="name" value="{{ username }}" required><br>

            <label for="password">Password:</label>
            <input type="password" name="password" id="password" required><button type="submit"> Create Account </button> <br>
        </form>
        <br>{{ error_message }}
    </div>
</div>

<div class="button-container">
    <a href="{{ url_for('user_bp.home') }}">
        <button class="bottom-right-button">Back to Homepage</button>
    </a>

    <a href="{{ url_for('user_bp.list_users') }}">
        <button class="bottom-right-button">Back to all users</button>
    </a>
</div>

</body>
</html>

templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Password</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='update-password-style.css') }}">
</head>
<body>
<div class="title">
    <h1>Update Password</h1>
</div>

<div class="add-user-box">
    <div class="enter-user-box">
        <form method="POST" >
            <label for="current_password">Current password:</label>
            <input type="password" name="current_password" id="current_password" required><br>

            <label for="new_password">New password:</label>
            <input type="password" name="new_password" id="new_password" required>
            <button type="submit">Update</button> <br>
        </form>
        <br>{{ error_message }}
    </div>
</div>

<div class="button-container">
    <a href="{{ url_for('movie_bp.user_movies', user_id=user_id) }}">
        <button class="bottom-right-button">Back to my Movies</button>
    </a>

    <a href="{{ url_for('user_bp.home') }}">
        <button class="bottom-right-button">Back to Homepage</button>
    </a>

    <a href="{{ url_for('user_bp.list_users') }}">
        <button class="bottom-right-button">Back to all users</button>
    </a>
</div>

</body>
</html>

templates/edit_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Review</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='edit-review-style.css') }}">
</head>
<body>

<div class="title">
    <h1>Edit Review</h1>
</div>

<div class="edit-review-box">
    <div class="enter-review-box">
        <form method="POST" >
            <label for="rating">Rating:</label>
            <input type="number" name="rating" id="rating" value="{{ review['rating'] }}" min="1" max="10" step="0.1" required><br>
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" value="{{ review['review_title'] }}" required><br>
            <label for="text">Review:</label>
            <textarea name="text" id="text" rows="4" required>{{ review['review_text'] }}</textarea><br>
            <button type="submit">Save Changes</button>
        </form>
    </div>
</div>

<div class="button-container">
    <a href="{{ url_for('review_bp.movie_details', movie_id=movie_id) }}">
        <button class="bottom-right-button">Back to Movie Details</button>
    </a>
</div>

</body>
</html>

templates/email_reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password reset email</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
</head>
<body>
<div class="title">
    <h1>Password Reset instructions</h1>
</div>
    <p>You are receiving this email as you requested a password reset for your account in the Moviepedia app.</p>
    <p> Please login to the app with the following temporary password:</p>
    <p><strong>{{ new_password }}</strong></p>
    <p>Follow the instructions below to change your password:</p>
    <ol>
        <li>In the top right corner of your profile, click on "Settings".</li>
        <li>In "Manage Account", click on "Change Password" and use the temporary password to choose a new password.</li>
    </ol>
</body>
</html>

templates/general_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
</head>
<body>
<div class="title">
    <h1>Error</h1>
</div>

<p>{{ error_message }}</p>

<div class="buttons-container">
    <a href="{{ url_for('user_bp.home') }}">
        <button class="top-right-button">Back to Homepage</button>
    </a>
</div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='add-user-style.css') }}">
</head>
<body>

<div class="title">
    <h1>Login</h1>
</div>

<div class="add-user-box">
    <div class="enter-user-box">
        <form method="POST">
            <label for="username">Username:</label>
            <input type="text" name="username" id="username" value="{% if request.args.get('username') %}{{ request.args.get('username') }}{% endif %}" required><br>
            <label for="password">Password:</label>
            <input type="password" name="password" id="password" required><button type="submit">Login</button>  <br>
        </form>
        <div class="container">
        <a href="{{ url_for('email_bp.forgot_password') }}"> Forgot password?</a>
        </div>
        <br>{{error_message}}
    </div>
</div>

<div class="button-container">
    <a href="{{ url_for('user_bp.home') }}">
        <button class="bottom-right-button">Back to Homepage</button>
    </a>

    <a href="{{ url_for('user_bp.list_users') }}">
        <button class="bottom-right-button">All users</button>
    </a>

    <a href="{{ url_for('user_bp.add_user') }}">
        <button class="bottom-right-button">New User</button>
    </a>
</div>
</body>
</html>

templates/update_movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Movie</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='update-movie-style.css') }}">
</head>
<body>
<div class="title">
     <h1>Update Movie: {{ movie['title'] }}</h1>
</div>

<div class="update-movie">
    <form method="POST">
        <div class="update-parameter">
            <label for="year">Year:</label>
            <input type="number" name="year" value="{{ movie['year'] }}" required><br>
        </div>

        <div class="update-parameter">
            <label for="director">Director:</label>
            <input type="text" name="director" value="{{ movie['director'] }}" required><br>
        </div>

        <div class="update-parameter">
            <label for="rating">Rating:</label>
            <input type="text" name="rating" value="{{ movie['rating'] }}" required><br>
        </div>

        <div class="update-parameter">
            <label for="poster">Poster:</label>
            <input type="text" name="poster" value="{{ movie['poster'] }}" required><br>
        </div>

        <div class="update-parameter">
            <label for="imdb_link">Imdb link:</label>
            <input type="text" name="imdb_link" value="{{ movie['movie_link'] }}" required><br>
        </div>

        <input type="submit" value="Update">
    </form>
</div>

<div class="button-container">
    <a href="{{ url_for('movie_bp.user_movies', user_id=user_id) }}">
        <button class="bottom-right-button">Back to my Movies</button>
    </a>

    <a href="{{ url_for('user_bp.home') }}">
        <button class="bottom-right-button">Back to Homepage</button>
    </a>

    <a href="{{ url_for('user_bp.list_users') }}">
        <button class="bottom-right-button">Back to all users</button>
    </a>
</div>
</body>
</html>

templates/user_movies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Movies</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='movies-grid-style.css') }}">
</head>
<body>

    <div class="list-movies-title">
        <h1>{{ user_name }}'s Moviepedia</h1>
        <a href="{{ url_for('user_bp.manage_account', user_id=user_id) }}" class="icon-link">
            <img src="{{ url_for('static', filename='settings_icon.png') }}" alt="Settings Icon" class="icon-image" />
        </a>
        <div class="gif-container">
            <form action="{{url_for('email_bp.ai_recommendations', user_id=user_id)}}" method="post" onsubmit="return confirm('By clicking ok you will receive an email from us with movie recommendations')">
                <button type="submit" name="submit" class="gif-button">
                    <img src="{{ url_for('static', filename='duck.gif') }}" alt="GIF Button">
                    <p class="message"> Not sure what to watch next? <br> Have our Duck send you some personalized ideas! </p>
                </button>
            </form>
        </div>
    </div>

    <div class="sorting-container">
    <div class="sorting-form">
        <form action="{{ url_for('movie_bp.user_movies', user_id=user_id) }}" method="get">
            <label for="sort">Sort by:</label>
            <select name="sort" id="sort" onchange="this.form.submit()" class="custom-dropdown">
                <option disabled selected value="">Select an option</option>
                <option value="date_added"> Date Added </option>
                <option value="director"> Director </option>
                <option value="rating">Rating</option>
                <option value="year">Year</option>
                <option value="title">Title</option>
            </select>
        </form>
    </div>
</div>

        <div class="flash-messages">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="flash-message">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    </div>

    <div>
        <ol class="movie-grid">
            {% for movie in movies %}
            <li>
                <div class="movie">
                    <div class="movie-buttons">
                        <a href="{{ url_for('review_bp.movie_details', movie_id=movie['id']) }}">
                            <button type="button" class="details-button">Details</button>
                        </a>
                        <a href="{{ url_for('movie_bp.update_movie', user_id=user_id, movie_id=movie['id']) }}">
                            <button type="button" class="update-button">Edit</button>
                        </a>
                        <form action="{{ url_for('movie_bp.delete_movie', user_id=user_id, movie_id=movie['id']) }}" method="post" onsubmit="return confirm('Are you sure you want to delete this movie?')">
                            <input type="hidden" name="_method" value="delete">
                            <button type="submit" class="delete-link"> X </button>
                        </form>
                    </div>
                    <a href={{movie['movie_link']}}>
                        <div class="movie-rating">{{ movie['rating'] }}</div>
                        <img class="movie-poster" src={{movie['poster']}}/>
                    </a>
                    <div class="movie-title">{{ movie['title'] }} - {{ movie['year'] }} </div>
                </div>
            </li>
            {% endfor %}
        </ol>

    </div>

    <div class="button-container">
        <a href="{{ url_for('movie_bp.add_movie', user_id=user_id) }}">
            <button class="bottom-right-button">Add Movie</button>
        </a>
        <a href="{{ url_for('user_bp.home') }}">
            <button class="top-right-button">Back to Homepage</button>
        </a>
        <a href="{{ url_for('user_bp.list_users') }}">
            <button class="bottom-right-button">Back to all users</button>
        </a>

        <a href="{{ url_for('user_bp.logout') }}">
            <button class="bottom-right-button">Logout</button>
        </a>
    </div>
</body>
</html>

templates/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users - MovieWeb App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='user-list-style.css') }}">
</head>
<body>
<div class="title">
    <h1>Users</h1>
</div>
<div class="users-list">
    <ul>
        {% for user in users %}
            <li>
                {% if current_user.is_authenticated and user['id'] == current_user.id %}
                    <a href="{{ url_for('movie_bp.user_movies', user_id=current_user.id) }}">{{ user['name'] }}</a>
                {% else %}
                    <a href="{{ url_for('user_bp.login', username=user['name']) }}">{{ user['name'] }}</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</div>
<div class="buttons-bar">
    <div class="buttons-container">
        <a href="{{ url_for('user_bp.add_user') }}">
            <button>Sign up</button>
        </a>
        <a href="{{ url_for('user_bp.home') }}">
            <button>Back to Homepage</button>
        </a>
         {% if current_user.is_authenticated %}
            <a href="{{ url_for('user_bp.logout') }}">
                <button class="bottom-right-button">Logout</button>
            </a>
        {% else %}
            <a href="{{ url_for('user_bp.login') }}">
                <button>Login</button>
            </a>
        {% endif %}
    </div>
</div>
</body>
</html>